#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuynhVanThao_141800706
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyThuVien")]
	public partial class QLTVDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblChuDe(tblChuDe instance);
    partial void UpdatetblChuDe(tblChuDe instance);
    partial void DeletetblChuDe(tblChuDe instance);
    partial void InserttblPhieuMuon(tblPhieuMuon instance);
    partial void UpdatetblPhieuMuon(tblPhieuMuon instance);
    partial void DeletetblPhieuMuon(tblPhieuMuon instance);
    partial void InserttblSach(tblSach instance);
    partial void UpdatetblSach(tblSach instance);
    partial void DeletetblSach(tblSach instance);
    partial void InserttblTacGia(tblTacGia instance);
    partial void UpdatetblTacGia(tblTacGia instance);
    partial void DeletetblTacGia(tblTacGia instance);
    partial void InserttblSinhVien(tblSinhVien instance);
    partial void UpdatetblSinhVien(tblSinhVien instance);
    partial void DeletetblSinhVien(tblSinhVien instance);
    partial void InserttblThuThu(tblThuThu instance);
    partial void UpdatetblThuThu(tblThuThu instance);
    partial void DeletetblThuThu(tblThuThu instance);
    partial void InserttblViTriSach(tblViTriSach instance);
    partial void UpdatetblViTriSach(tblViTriSach instance);
    partial void DeletetblViTriSach(tblViTriSach instance);
    #endregion
		
		public QLTVDataContext() : 
				base(global::HuynhVanThao_141800706.Properties.Settings.Default.QuanLyThuVienConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLTVDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLTVDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLTVDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLTVDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblChuDe> tblChuDes
		{
			get
			{
				return this.GetTable<tblChuDe>();
			}
		}
		
		public System.Data.Linq.Table<tblPhieuMuon> tblPhieuMuons
		{
			get
			{
				return this.GetTable<tblPhieuMuon>();
			}
		}
		
		public System.Data.Linq.Table<tblSach> tblSaches
		{
			get
			{
				return this.GetTable<tblSach>();
			}
		}
		
		public System.Data.Linq.Table<tblTacGia> tblTacGias
		{
			get
			{
				return this.GetTable<tblTacGia>();
			}
		}
		
		public System.Data.Linq.Table<tblSinhVien> tblSinhViens
		{
			get
			{
				return this.GetTable<tblSinhVien>();
			}
		}
		
		public System.Data.Linq.Table<tblThuThu> tblThuThus
		{
			get
			{
				return this.GetTable<tblThuThu>();
			}
		}
		
		public System.Data.Linq.Table<tblViTriSach> tblViTriSaches
		{
			get
			{
				return this.GetTable<tblViTriSach>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_LayDuLieuSach")]
		public ISingleResult<sp_LayDuLieuSachResult> sp_LayDuLieuSach()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_LayDuLieuSachResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_TimKiemCa2")]
		public ISingleResult<sp_TimKiemCa2Result> sp_TimKiemCa2([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaSV1", DbType="NVarChar(20)")] string maSV1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HoTenSV1", DbType="NVarChar(100)")] string hoTenSV1)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maSV1, hoTenSV1);
			return ((ISingleResult<sp_TimKiemCa2Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_TimKiemChuDe")]
		public ISingleResult<sp_TimKiemChuDeResult> sp_TimKiemChuDe([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ChuDe", DbType="NVarChar(50)")] string chuDe)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), chuDe);
			return ((ISingleResult<sp_TimKiemChuDeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_TimKiemHoTenSV")]
		public ISingleResult<sp_TimKiemHoTenSVResult> sp_TimKiemHoTenSV([global::System.Data.Linq.Mapping.ParameterAttribute(Name="HoTenSV", DbType="NVarChar(100)")] string hoTenSV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), hoTenSV);
			return ((ISingleResult<sp_TimKiemHoTenSVResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_TimKiemMaSV")]
		public ISingleResult<sp_TimKiemMaSVResult> sp_TimKiemMaSV([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaSV", DbType="NVarChar(20)")] string maSV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maSV);
			return ((ISingleResult<sp_TimKiemMaSVResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_TimKiemTacGia")]
		public ISingleResult<sp_TimKiemTacGiaResult> sp_TimKiemTacGia([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TacGia", DbType="NVarChar(50)")] string tacGia)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tacGia);
			return ((ISingleResult<sp_TimKiemTacGiaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_TimKiemTenSach")]
		public ISingleResult<sp_TimKiemTenSachResult> sp_TimKiemTenSach([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenSach", DbType="NVarChar(100)")] string tenSach)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenSach);
			return ((ISingleResult<sp_TimKiemTenSachResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_TongSoLuongSach")]
		public ISingleResult<sp_TongSoLuongSachResult> sp_TongSoLuongSach()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_TongSoLuongSachResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_TongGiaTriSach")]
		public ISingleResult<sp_TongGiaTriSachResult> sp_TongGiaTriSach()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_TongGiaTriSachResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SoLuongSachDangMuon")]
		public ISingleResult<sp_SoLuongSachDangMuonResult> sp_SoLuongSachDangMuon()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_SoLuongSachDangMuonResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SoLuongSachDaMuon")]
		public ISingleResult<sp_SoLuongSachDaMuonResult> sp_SoLuongSachDaMuon()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_SoLuongSachDaMuonResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_TimKiemTheoMa")]
		public ISingleResult<sp_TimKiemTheoMaResult> sp_TimKiemTheoMa([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string text)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), text);
			return ((ISingleResult<sp_TimKiemTheoMaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SoLuongDGDangMuon")]
		public ISingleResult<sp_SoLuongDGDangMuonResult> sp_SoLuongDGDangMuon()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_SoLuongDGDangMuonResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SoLuongDGQuaHan")]
		public ISingleResult<sp_SoLuongDGQuaHanResult> sp_SoLuongDGQuaHan()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_SoLuongDGQuaHanResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblChuDe")]
	public partial class tblChuDe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenChuDe;
		
		private string _GhiChu;
		
		private EntitySet<tblSach> _tblSaches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenChuDeChanging(string value);
    partial void OnTenChuDeChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public tblChuDe()
		{
			this._tblSaches = new EntitySet<tblSach>(new Action<tblSach>(this.attach_tblSaches), new Action<tblSach>(this.detach_tblSaches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenChuDe", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenChuDe
		{
			get
			{
				return this._TenChuDe;
			}
			set
			{
				if ((this._TenChuDe != value))
				{
					this.OnTenChuDeChanging(value);
					this.SendPropertyChanging();
					this._TenChuDe = value;
					this.SendPropertyChanged("TenChuDe");
					this.OnTenChuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblChuDe_tblSach", Storage="_tblSaches", ThisKey="TenChuDe", OtherKey="ChuDe")]
		public EntitySet<tblSach> tblSaches
		{
			get
			{
				return this._tblSaches;
			}
			set
			{
				this._tblSaches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblSaches(tblSach entity)
		{
			this.SendPropertyChanging();
			entity.tblChuDe = this;
		}
		
		private void detach_tblSaches(tblSach entity)
		{
			this.SendPropertyChanging();
			entity.tblChuDe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPhieuMuon")]
	public partial class tblPhieuMuon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPhieuMuon;
		
		private string _MaSV;
		
		private string _MaSach;
		
		private string _NguoiLap;
		
		private string _SoLuong;
		
		private System.DateTime _NgayMuon;
		
		private System.DateTime _NgayTra;
		
		private string _GhiChu;
		
		private EntityRef<tblSach> _tblSach;
		
		private EntityRef<tblSinhVien> _tblSinhVien;
		
		private EntityRef<tblThuThu> _tblThuThu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhieuMuonChanging(string value);
    partial void OnMaPhieuMuonChanged();
    partial void OnMaSVChanging(string value);
    partial void OnMaSVChanged();
    partial void OnMaSachChanging(string value);
    partial void OnMaSachChanged();
    partial void OnNguoiLapChanging(string value);
    partial void OnNguoiLapChanged();
    partial void OnSoLuongChanging(string value);
    partial void OnSoLuongChanged();
    partial void OnNgayMuonChanging(System.DateTime value);
    partial void OnNgayMuonChanged();
    partial void OnNgayTraChanging(System.DateTime value);
    partial void OnNgayTraChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public tblPhieuMuon()
		{
			this._tblSach = default(EntityRef<tblSach>);
			this._tblSinhVien = default(EntityRef<tblSinhVien>);
			this._tblThuThu = default(EntityRef<tblThuThu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieuMuon", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPhieuMuon
		{
			get
			{
				return this._MaPhieuMuon;
			}
			set
			{
				if ((this._MaPhieuMuon != value))
				{
					this.OnMaPhieuMuonChanging(value);
					this.SendPropertyChanging();
					this._MaPhieuMuon = value;
					this.SendPropertyChanged("MaPhieuMuon");
					this.OnMaPhieuMuonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSV", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MaSV
		{
			get
			{
				return this._MaSV;
			}
			set
			{
				if ((this._MaSV != value))
				{
					if (this._tblSinhVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSVChanging(value);
					this.SendPropertyChanging();
					this._MaSV = value;
					this.SendPropertyChanged("MaSV");
					this.OnMaSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSach", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MaSach
		{
			get
			{
				return this._MaSach;
			}
			set
			{
				if ((this._MaSach != value))
				{
					if (this._tblSach.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSachChanging(value);
					this.SendPropertyChanging();
					this._MaSach = value;
					this.SendPropertyChanged("MaSach");
					this.OnMaSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiLap", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string NguoiLap
		{
			get
			{
				return this._NguoiLap;
			}
			set
			{
				if ((this._NguoiLap != value))
				{
					if (this._tblThuThu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNguoiLapChanging(value);
					this.SendPropertyChanging();
					this._NguoiLap = value;
					this.SendPropertyChanged("NguoiLap");
					this.OnNguoiLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayMuon", DbType="Date NOT NULL")]
		public System.DateTime NgayMuon
		{
			get
			{
				return this._NgayMuon;
			}
			set
			{
				if ((this._NgayMuon != value))
				{
					this.OnNgayMuonChanging(value);
					this.SendPropertyChanging();
					this._NgayMuon = value;
					this.SendPropertyChanged("NgayMuon");
					this.OnNgayMuonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTra", DbType="Date NOT NULL")]
		public System.DateTime NgayTra
		{
			get
			{
				return this._NgayTra;
			}
			set
			{
				if ((this._NgayTra != value))
				{
					this.OnNgayTraChanging(value);
					this.SendPropertyChanging();
					this._NgayTra = value;
					this.SendPropertyChanged("NgayTra");
					this.OnNgayTraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(200)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSach_tblPhieuMuon", Storage="_tblSach", ThisKey="MaSach", OtherKey="MaSach", IsForeignKey=true)]
		public tblSach tblSach
		{
			get
			{
				return this._tblSach.Entity;
			}
			set
			{
				tblSach previousValue = this._tblSach.Entity;
				if (((previousValue != value) 
							|| (this._tblSach.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblSach.Entity = null;
						previousValue.tblPhieuMuons.Remove(this);
					}
					this._tblSach.Entity = value;
					if ((value != null))
					{
						value.tblPhieuMuons.Add(this);
						this._MaSach = value.MaSach;
					}
					else
					{
						this._MaSach = default(string);
					}
					this.SendPropertyChanged("tblSach");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSinhVien_tblPhieuMuon", Storage="_tblSinhVien", ThisKey="MaSV", OtherKey="MaSV", IsForeignKey=true)]
		public tblSinhVien tblSinhVien
		{
			get
			{
				return this._tblSinhVien.Entity;
			}
			set
			{
				tblSinhVien previousValue = this._tblSinhVien.Entity;
				if (((previousValue != value) 
							|| (this._tblSinhVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblSinhVien.Entity = null;
						previousValue.tblPhieuMuons.Remove(this);
					}
					this._tblSinhVien.Entity = value;
					if ((value != null))
					{
						value.tblPhieuMuons.Add(this);
						this._MaSV = value.MaSV;
					}
					else
					{
						this._MaSV = default(string);
					}
					this.SendPropertyChanged("tblSinhVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblThuThu_tblPhieuMuon", Storage="_tblThuThu", ThisKey="NguoiLap", OtherKey="MaTT", IsForeignKey=true)]
		public tblThuThu tblThuThu
		{
			get
			{
				return this._tblThuThu.Entity;
			}
			set
			{
				tblThuThu previousValue = this._tblThuThu.Entity;
				if (((previousValue != value) 
							|| (this._tblThuThu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblThuThu.Entity = null;
						previousValue.tblPhieuMuons.Remove(this);
					}
					this._tblThuThu.Entity = value;
					if ((value != null))
					{
						value.tblPhieuMuons.Add(this);
						this._NguoiLap = value.MaTT;
					}
					else
					{
						this._NguoiLap = default(string);
					}
					this.SendPropertyChanged("tblThuThu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSach")]
	public partial class tblSach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSach;
		
		private string _TenSach;
		
		private string _ChuDe;
		
		private string _TacGia;
		
		private string _NhaXB;
		
		private string _NamXB;
		
		private string _SoLuong;
		
		private string _DonGia;
		
		private EntitySet<tblPhieuMuon> _tblPhieuMuons;
		
		private EntitySet<tblViTriSach> _tblViTriSaches;
		
		private EntityRef<tblChuDe> _tblChuDe;
		
		private EntityRef<tblTacGia> _tblTacGia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSachChanging(string value);
    partial void OnMaSachChanged();
    partial void OnTenSachChanging(string value);
    partial void OnTenSachChanged();
    partial void OnChuDeChanging(string value);
    partial void OnChuDeChanged();
    partial void OnTacGiaChanging(string value);
    partial void OnTacGiaChanged();
    partial void OnNhaXBChanging(string value);
    partial void OnNhaXBChanged();
    partial void OnNamXBChanging(string value);
    partial void OnNamXBChanged();
    partial void OnSoLuongChanging(string value);
    partial void OnSoLuongChanged();
    partial void OnDonGiaChanging(string value);
    partial void OnDonGiaChanged();
    #endregion
		
		public tblSach()
		{
			this._tblPhieuMuons = new EntitySet<tblPhieuMuon>(new Action<tblPhieuMuon>(this.attach_tblPhieuMuons), new Action<tblPhieuMuon>(this.detach_tblPhieuMuons));
			this._tblViTriSaches = new EntitySet<tblViTriSach>(new Action<tblViTriSach>(this.attach_tblViTriSaches), new Action<tblViTriSach>(this.detach_tblViTriSaches));
			this._tblChuDe = default(EntityRef<tblChuDe>);
			this._tblTacGia = default(EntityRef<tblTacGia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSach", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSach
		{
			get
			{
				return this._MaSach;
			}
			set
			{
				if ((this._MaSach != value))
				{
					this.OnMaSachChanging(value);
					this.SendPropertyChanging();
					this._MaSach = value;
					this.SendPropertyChanged("MaSach");
					this.OnMaSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSach", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenSach
		{
			get
			{
				return this._TenSach;
			}
			set
			{
				if ((this._TenSach != value))
				{
					this.OnTenSachChanging(value);
					this.SendPropertyChanging();
					this._TenSach = value;
					this.SendPropertyChanged("TenSach");
					this.OnTenSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuDe", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ChuDe
		{
			get
			{
				return this._ChuDe;
			}
			set
			{
				if ((this._ChuDe != value))
				{
					if (this._tblChuDe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnChuDeChanging(value);
					this.SendPropertyChanging();
					this._ChuDe = value;
					this.SendPropertyChanged("ChuDe");
					this.OnChuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TacGia", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TacGia
		{
			get
			{
				return this._TacGia;
			}
			set
			{
				if ((this._TacGia != value))
				{
					if (this._tblTacGia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTacGiaChanging(value);
					this.SendPropertyChanging();
					this._TacGia = value;
					this.SendPropertyChanged("TacGia");
					this.OnTacGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhaXB", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NhaXB
		{
			get
			{
				return this._NhaXB;
			}
			set
			{
				if ((this._NhaXB != value))
				{
					this.OnNhaXBChanging(value);
					this.SendPropertyChanging();
					this._NhaXB = value;
					this.SendPropertyChanged("NhaXB");
					this.OnNhaXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamXB", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string NamXB
		{
			get
			{
				return this._NamXB;
			}
			set
			{
				if ((this._NamXB != value))
				{
					this.OnNamXBChanging(value);
					this.SendPropertyChanging();
					this._NamXB = value;
					this.SendPropertyChanged("NamXB");
					this.OnNamXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSach_tblPhieuMuon", Storage="_tblPhieuMuons", ThisKey="MaSach", OtherKey="MaSach")]
		public EntitySet<tblPhieuMuon> tblPhieuMuons
		{
			get
			{
				return this._tblPhieuMuons;
			}
			set
			{
				this._tblPhieuMuons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSach_tblViTriSach", Storage="_tblViTriSaches", ThisKey="MaSach", OtherKey="MaSach")]
		public EntitySet<tblViTriSach> tblViTriSaches
		{
			get
			{
				return this._tblViTriSaches;
			}
			set
			{
				this._tblViTriSaches.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblChuDe_tblSach", Storage="_tblChuDe", ThisKey="ChuDe", OtherKey="TenChuDe", IsForeignKey=true)]
		public tblChuDe tblChuDe
		{
			get
			{
				return this._tblChuDe.Entity;
			}
			set
			{
				tblChuDe previousValue = this._tblChuDe.Entity;
				if (((previousValue != value) 
							|| (this._tblChuDe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblChuDe.Entity = null;
						previousValue.tblSaches.Remove(this);
					}
					this._tblChuDe.Entity = value;
					if ((value != null))
					{
						value.tblSaches.Add(this);
						this._ChuDe = value.TenChuDe;
					}
					else
					{
						this._ChuDe = default(string);
					}
					this.SendPropertyChanged("tblChuDe");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblTacGia_tblSach", Storage="_tblTacGia", ThisKey="TacGia", OtherKey="TenTacGia", IsForeignKey=true)]
		public tblTacGia tblTacGia
		{
			get
			{
				return this._tblTacGia.Entity;
			}
			set
			{
				tblTacGia previousValue = this._tblTacGia.Entity;
				if (((previousValue != value) 
							|| (this._tblTacGia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblTacGia.Entity = null;
						previousValue.tblSaches.Remove(this);
					}
					this._tblTacGia.Entity = value;
					if ((value != null))
					{
						value.tblSaches.Add(this);
						this._TacGia = value.TenTacGia;
					}
					else
					{
						this._TacGia = default(string);
					}
					this.SendPropertyChanged("tblTacGia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblPhieuMuons(tblPhieuMuon entity)
		{
			this.SendPropertyChanging();
			entity.tblSach = this;
		}
		
		private void detach_tblPhieuMuons(tblPhieuMuon entity)
		{
			this.SendPropertyChanging();
			entity.tblSach = null;
		}
		
		private void attach_tblViTriSaches(tblViTriSach entity)
		{
			this.SendPropertyChanging();
			entity.tblSach = this;
		}
		
		private void detach_tblViTriSaches(tblViTriSach entity)
		{
			this.SendPropertyChanging();
			entity.tblSach = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblTacGia")]
	public partial class tblTacGia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenTacGia;
		
		private string _GhiChu;
		
		private EntitySet<tblSach> _tblSaches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenTacGiaChanging(string value);
    partial void OnTenTacGiaChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public tblTacGia()
		{
			this._tblSaches = new EntitySet<tblSach>(new Action<tblSach>(this.attach_tblSaches), new Action<tblSach>(this.detach_tblSaches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTacGia", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenTacGia
		{
			get
			{
				return this._TenTacGia;
			}
			set
			{
				if ((this._TenTacGia != value))
				{
					this.OnTenTacGiaChanging(value);
					this.SendPropertyChanging();
					this._TenTacGia = value;
					this.SendPropertyChanged("TenTacGia");
					this.OnTenTacGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblTacGia_tblSach", Storage="_tblSaches", ThisKey="TenTacGia", OtherKey="TacGia")]
		public EntitySet<tblSach> tblSaches
		{
			get
			{
				return this._tblSaches;
			}
			set
			{
				this._tblSaches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblSaches(tblSach entity)
		{
			this.SendPropertyChanging();
			entity.tblTacGia = this;
		}
		
		private void detach_tblSaches(tblSach entity)
		{
			this.SendPropertyChanging();
			entity.tblTacGia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSinhVien")]
	public partial class tblSinhVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSV;
		
		private string _HoTenSV;
		
		private string _Lop;
		
		private string _GioiTinhSV;
		
		private System.DateTime _NgaySinhSV;
		
		private string _SdtSV;
		
		private string _MatKhauSV;
		
		private EntitySet<tblPhieuMuon> _tblPhieuMuons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSVChanging(string value);
    partial void OnMaSVChanged();
    partial void OnHoTenSVChanging(string value);
    partial void OnHoTenSVChanged();
    partial void OnLopChanging(string value);
    partial void OnLopChanged();
    partial void OnGioiTinhSVChanging(string value);
    partial void OnGioiTinhSVChanged();
    partial void OnNgaySinhSVChanging(System.DateTime value);
    partial void OnNgaySinhSVChanged();
    partial void OnSdtSVChanging(string value);
    partial void OnSdtSVChanged();
    partial void OnMatKhauSVChanging(string value);
    partial void OnMatKhauSVChanged();
    #endregion
		
		public tblSinhVien()
		{
			this._tblPhieuMuons = new EntitySet<tblPhieuMuon>(new Action<tblPhieuMuon>(this.attach_tblPhieuMuons), new Action<tblPhieuMuon>(this.detach_tblPhieuMuons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSV", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSV
		{
			get
			{
				return this._MaSV;
			}
			set
			{
				if ((this._MaSV != value))
				{
					this.OnMaSVChanging(value);
					this.SendPropertyChanging();
					this._MaSV = value;
					this.SendPropertyChanged("MaSV");
					this.OnMaSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTenSV", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string HoTenSV
		{
			get
			{
				return this._HoTenSV;
			}
			set
			{
				if ((this._HoTenSV != value))
				{
					this.OnHoTenSVChanging(value);
					this.SendPropertyChanging();
					this._HoTenSV = value;
					this.SendPropertyChanged("HoTenSV");
					this.OnHoTenSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lop", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Lop
		{
			get
			{
				return this._Lop;
			}
			set
			{
				if ((this._Lop != value))
				{
					this.OnLopChanging(value);
					this.SendPropertyChanging();
					this._Lop = value;
					this.SendPropertyChanged("Lop");
					this.OnLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinhSV", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string GioiTinhSV
		{
			get
			{
				return this._GioiTinhSV;
			}
			set
			{
				if ((this._GioiTinhSV != value))
				{
					this.OnGioiTinhSVChanging(value);
					this.SendPropertyChanging();
					this._GioiTinhSV = value;
					this.SendPropertyChanged("GioiTinhSV");
					this.OnGioiTinhSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinhSV", DbType="Date NOT NULL")]
		public System.DateTime NgaySinhSV
		{
			get
			{
				return this._NgaySinhSV;
			}
			set
			{
				if ((this._NgaySinhSV != value))
				{
					this.OnNgaySinhSVChanging(value);
					this.SendPropertyChanging();
					this._NgaySinhSV = value;
					this.SendPropertyChanged("NgaySinhSV");
					this.OnNgaySinhSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SdtSV", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string SdtSV
		{
			get
			{
				return this._SdtSV;
			}
			set
			{
				if ((this._SdtSV != value))
				{
					this.OnSdtSVChanging(value);
					this.SendPropertyChanging();
					this._SdtSV = value;
					this.SendPropertyChanged("SdtSV");
					this.OnSdtSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhauSV", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MatKhauSV
		{
			get
			{
				return this._MatKhauSV;
			}
			set
			{
				if ((this._MatKhauSV != value))
				{
					this.OnMatKhauSVChanging(value);
					this.SendPropertyChanging();
					this._MatKhauSV = value;
					this.SendPropertyChanged("MatKhauSV");
					this.OnMatKhauSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSinhVien_tblPhieuMuon", Storage="_tblPhieuMuons", ThisKey="MaSV", OtherKey="MaSV")]
		public EntitySet<tblPhieuMuon> tblPhieuMuons
		{
			get
			{
				return this._tblPhieuMuons;
			}
			set
			{
				this._tblPhieuMuons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblPhieuMuons(tblPhieuMuon entity)
		{
			this.SendPropertyChanging();
			entity.tblSinhVien = this;
		}
		
		private void detach_tblPhieuMuons(tblPhieuMuon entity)
		{
			this.SendPropertyChanging();
			entity.tblSinhVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblThuThu")]
	public partial class tblThuThu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTT;
		
		private string _HoTenTT;
		
		private string _GioiTinhTT;
		
		private System.DateTime _NgaySinhTT;
		
		private string _SdtTT;
		
		private string _DiaChiTT;
		
		private string _MatKhauTT;
		
		private EntitySet<tblPhieuMuon> _tblPhieuMuons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTTChanging(string value);
    partial void OnMaTTChanged();
    partial void OnHoTenTTChanging(string value);
    partial void OnHoTenTTChanged();
    partial void OnGioiTinhTTChanging(string value);
    partial void OnGioiTinhTTChanged();
    partial void OnNgaySinhTTChanging(System.DateTime value);
    partial void OnNgaySinhTTChanged();
    partial void OnSdtTTChanging(string value);
    partial void OnSdtTTChanged();
    partial void OnDiaChiTTChanging(string value);
    partial void OnDiaChiTTChanged();
    partial void OnMatKhauTTChanging(string value);
    partial void OnMatKhauTTChanged();
    #endregion
		
		public tblThuThu()
		{
			this._tblPhieuMuons = new EntitySet<tblPhieuMuon>(new Action<tblPhieuMuon>(this.attach_tblPhieuMuons), new Action<tblPhieuMuon>(this.detach_tblPhieuMuons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTT", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTT
		{
			get
			{
				return this._MaTT;
			}
			set
			{
				if ((this._MaTT != value))
				{
					this.OnMaTTChanging(value);
					this.SendPropertyChanging();
					this._MaTT = value;
					this.SendPropertyChanged("MaTT");
					this.OnMaTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTenTT", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string HoTenTT
		{
			get
			{
				return this._HoTenTT;
			}
			set
			{
				if ((this._HoTenTT != value))
				{
					this.OnHoTenTTChanging(value);
					this.SendPropertyChanging();
					this._HoTenTT = value;
					this.SendPropertyChanged("HoTenTT");
					this.OnHoTenTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinhTT", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string GioiTinhTT
		{
			get
			{
				return this._GioiTinhTT;
			}
			set
			{
				if ((this._GioiTinhTT != value))
				{
					this.OnGioiTinhTTChanging(value);
					this.SendPropertyChanging();
					this._GioiTinhTT = value;
					this.SendPropertyChanged("GioiTinhTT");
					this.OnGioiTinhTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinhTT", DbType="Date NOT NULL")]
		public System.DateTime NgaySinhTT
		{
			get
			{
				return this._NgaySinhTT;
			}
			set
			{
				if ((this._NgaySinhTT != value))
				{
					this.OnNgaySinhTTChanging(value);
					this.SendPropertyChanging();
					this._NgaySinhTT = value;
					this.SendPropertyChanged("NgaySinhTT");
					this.OnNgaySinhTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SdtTT", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string SdtTT
		{
			get
			{
				return this._SdtTT;
			}
			set
			{
				if ((this._SdtTT != value))
				{
					this.OnSdtTTChanging(value);
					this.SendPropertyChanging();
					this._SdtTT = value;
					this.SendPropertyChanged("SdtTT");
					this.OnSdtTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChiTT", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DiaChiTT
		{
			get
			{
				return this._DiaChiTT;
			}
			set
			{
				if ((this._DiaChiTT != value))
				{
					this.OnDiaChiTTChanging(value);
					this.SendPropertyChanging();
					this._DiaChiTT = value;
					this.SendPropertyChanged("DiaChiTT");
					this.OnDiaChiTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhauTT", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MatKhauTT
		{
			get
			{
				return this._MatKhauTT;
			}
			set
			{
				if ((this._MatKhauTT != value))
				{
					this.OnMatKhauTTChanging(value);
					this.SendPropertyChanging();
					this._MatKhauTT = value;
					this.SendPropertyChanged("MatKhauTT");
					this.OnMatKhauTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblThuThu_tblPhieuMuon", Storage="_tblPhieuMuons", ThisKey="MaTT", OtherKey="NguoiLap")]
		public EntitySet<tblPhieuMuon> tblPhieuMuons
		{
			get
			{
				return this._tblPhieuMuons;
			}
			set
			{
				this._tblPhieuMuons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblPhieuMuons(tblPhieuMuon entity)
		{
			this.SendPropertyChanging();
			entity.tblThuThu = this;
		}
		
		private void detach_tblPhieuMuons(tblPhieuMuon entity)
		{
			this.SendPropertyChanging();
			entity.tblThuThu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblViTriSach")]
	public partial class tblViTriSach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaViTri;
		
		private string _MaSach;
		
		private string _KhuVuc;
		
		private string _KeSach;
		
		private string _OSach;
		
		private EntityRef<tblSach> _tblSach;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaViTriChanging(string value);
    partial void OnMaViTriChanged();
    partial void OnMaSachChanging(string value);
    partial void OnMaSachChanged();
    partial void OnKhuVucChanging(string value);
    partial void OnKhuVucChanged();
    partial void OnKeSachChanging(string value);
    partial void OnKeSachChanged();
    partial void OnOSachChanging(string value);
    partial void OnOSachChanged();
    #endregion
		
		public tblViTriSach()
		{
			this._tblSach = default(EntityRef<tblSach>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaViTri", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaViTri
		{
			get
			{
				return this._MaViTri;
			}
			set
			{
				if ((this._MaViTri != value))
				{
					this.OnMaViTriChanging(value);
					this.SendPropertyChanging();
					this._MaViTri = value;
					this.SendPropertyChanged("MaViTri");
					this.OnMaViTriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSach", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MaSach
		{
			get
			{
				return this._MaSach;
			}
			set
			{
				if ((this._MaSach != value))
				{
					if (this._tblSach.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSachChanging(value);
					this.SendPropertyChanging();
					this._MaSach = value;
					this.SendPropertyChanged("MaSach");
					this.OnMaSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhuVuc", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string KhuVuc
		{
			get
			{
				return this._KhuVuc;
			}
			set
			{
				if ((this._KhuVuc != value))
				{
					this.OnKhuVucChanging(value);
					this.SendPropertyChanging();
					this._KhuVuc = value;
					this.SendPropertyChanged("KhuVuc");
					this.OnKhuVucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeSach", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string KeSach
		{
			get
			{
				return this._KeSach;
			}
			set
			{
				if ((this._KeSach != value))
				{
					this.OnKeSachChanging(value);
					this.SendPropertyChanging();
					this._KeSach = value;
					this.SendPropertyChanged("KeSach");
					this.OnKeSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OSach", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string OSach
		{
			get
			{
				return this._OSach;
			}
			set
			{
				if ((this._OSach != value))
				{
					this.OnOSachChanging(value);
					this.SendPropertyChanging();
					this._OSach = value;
					this.SendPropertyChanged("OSach");
					this.OnOSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSach_tblViTriSach", Storage="_tblSach", ThisKey="MaSach", OtherKey="MaSach", IsForeignKey=true)]
		public tblSach tblSach
		{
			get
			{
				return this._tblSach.Entity;
			}
			set
			{
				tblSach previousValue = this._tblSach.Entity;
				if (((previousValue != value) 
							|| (this._tblSach.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblSach.Entity = null;
						previousValue.tblViTriSaches.Remove(this);
					}
					this._tblSach.Entity = value;
					if ((value != null))
					{
						value.tblViTriSaches.Add(this);
						this._MaSach = value.MaSach;
					}
					else
					{
						this._MaSach = default(string);
					}
					this.SendPropertyChanged("tblSach");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class sp_LayDuLieuSachResult
	{
		
		private string _MaSach;
		
		private string _TenSach;
		
		private string _ChuDe;
		
		private string _TacGia;
		
		private string _NhaXB;
		
		private string _NamXB;
		
		private string _SoLuong;
		
		private string _DonGia;
		
		private string _MaViTri;
		
		private string _MaSach1;
		
		private string _KhuVuc;
		
		private string _KeSach;
		
		private string _OSach;
		
		public sp_LayDuLieuSachResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSach", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MaSach
		{
			get
			{
				return this._MaSach;
			}
			set
			{
				if ((this._MaSach != value))
				{
					this._MaSach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSach", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenSach
		{
			get
			{
				return this._TenSach;
			}
			set
			{
				if ((this._TenSach != value))
				{
					this._TenSach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuDe", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ChuDe
		{
			get
			{
				return this._ChuDe;
			}
			set
			{
				if ((this._ChuDe != value))
				{
					this._ChuDe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TacGia", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TacGia
		{
			get
			{
				return this._TacGia;
			}
			set
			{
				if ((this._TacGia != value))
				{
					this._TacGia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhaXB", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NhaXB
		{
			get
			{
				return this._NhaXB;
			}
			set
			{
				if ((this._NhaXB != value))
				{
					this._NhaXB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamXB", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string NamXB
		{
			get
			{
				return this._NamXB;
			}
			set
			{
				if ((this._NamXB != value))
				{
					this._NamXB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this._SoLuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this._DonGia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaViTri", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MaViTri
		{
			get
			{
				return this._MaViTri;
			}
			set
			{
				if ((this._MaViTri != value))
				{
					this._MaViTri = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSach1", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MaSach1
		{
			get
			{
				return this._MaSach1;
			}
			set
			{
				if ((this._MaSach1 != value))
				{
					this._MaSach1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhuVuc", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string KhuVuc
		{
			get
			{
				return this._KhuVuc;
			}
			set
			{
				if ((this._KhuVuc != value))
				{
					this._KhuVuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeSach", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string KeSach
		{
			get
			{
				return this._KeSach;
			}
			set
			{
				if ((this._KeSach != value))
				{
					this._KeSach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OSach", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string OSach
		{
			get
			{
				return this._OSach;
			}
			set
			{
				if ((this._OSach != value))
				{
					this._OSach = value;
				}
			}
		}
	}
	
	public partial class sp_TimKiemCa2Result
	{
		
		private string _MaSV;
		
		private string _HoTenSV;
		
		private string _Lop;
		
		private string _GioiTinhSV;
		
		private System.DateTime _NgaySinhSV;
		
		private string _SdtSV;
		
		private string _MatKhauSV;
		
		public sp_TimKiemCa2Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSV", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MaSV
		{
			get
			{
				return this._MaSV;
			}
			set
			{
				if ((this._MaSV != value))
				{
					this._MaSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTenSV", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string HoTenSV
		{
			get
			{
				return this._HoTenSV;
			}
			set
			{
				if ((this._HoTenSV != value))
				{
					this._HoTenSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lop", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Lop
		{
			get
			{
				return this._Lop;
			}
			set
			{
				if ((this._Lop != value))
				{
					this._Lop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinhSV", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string GioiTinhSV
		{
			get
			{
				return this._GioiTinhSV;
			}
			set
			{
				if ((this._GioiTinhSV != value))
				{
					this._GioiTinhSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinhSV", DbType="Date NOT NULL")]
		public System.DateTime NgaySinhSV
		{
			get
			{
				return this._NgaySinhSV;
			}
			set
			{
				if ((this._NgaySinhSV != value))
				{
					this._NgaySinhSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SdtSV", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string SdtSV
		{
			get
			{
				return this._SdtSV;
			}
			set
			{
				if ((this._SdtSV != value))
				{
					this._SdtSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhauSV", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MatKhauSV
		{
			get
			{
				return this._MatKhauSV;
			}
			set
			{
				if ((this._MatKhauSV != value))
				{
					this._MatKhauSV = value;
				}
			}
		}
	}
	
	public partial class sp_TimKiemChuDeResult
	{
		
		private string _MaSach;
		
		private string _TenSach;
		
		private string _ChuDe;
		
		private string _TacGia;
		
		private string _NhaXB;
		
		private string _NamXB;
		
		private string _SoLuong;
		
		private string _DonGia;
		
		private string _MaViTri;
		
		private string _MaSach1;
		
		private string _KhuVuc;
		
		private string _KeSach;
		
		private string _OSach;
		
		public sp_TimKiemChuDeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSach", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MaSach
		{
			get
			{
				return this._MaSach;
			}
			set
			{
				if ((this._MaSach != value))
				{
					this._MaSach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSach", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenSach
		{
			get
			{
				return this._TenSach;
			}
			set
			{
				if ((this._TenSach != value))
				{
					this._TenSach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuDe", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ChuDe
		{
			get
			{
				return this._ChuDe;
			}
			set
			{
				if ((this._ChuDe != value))
				{
					this._ChuDe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TacGia", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TacGia
		{
			get
			{
				return this._TacGia;
			}
			set
			{
				if ((this._TacGia != value))
				{
					this._TacGia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhaXB", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NhaXB
		{
			get
			{
				return this._NhaXB;
			}
			set
			{
				if ((this._NhaXB != value))
				{
					this._NhaXB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamXB", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string NamXB
		{
			get
			{
				return this._NamXB;
			}
			set
			{
				if ((this._NamXB != value))
				{
					this._NamXB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this._SoLuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this._DonGia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaViTri", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MaViTri
		{
			get
			{
				return this._MaViTri;
			}
			set
			{
				if ((this._MaViTri != value))
				{
					this._MaViTri = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSach1", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MaSach1
		{
			get
			{
				return this._MaSach1;
			}
			set
			{
				if ((this._MaSach1 != value))
				{
					this._MaSach1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhuVuc", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string KhuVuc
		{
			get
			{
				return this._KhuVuc;
			}
			set
			{
				if ((this._KhuVuc != value))
				{
					this._KhuVuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeSach", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string KeSach
		{
			get
			{
				return this._KeSach;
			}
			set
			{
				if ((this._KeSach != value))
				{
					this._KeSach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OSach", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string OSach
		{
			get
			{
				return this._OSach;
			}
			set
			{
				if ((this._OSach != value))
				{
					this._OSach = value;
				}
			}
		}
	}
	
	public partial class sp_TimKiemHoTenSVResult
	{
		
		private string _MaSV;
		
		private string _HoTenSV;
		
		private string _Lop;
		
		private string _GioiTinhSV;
		
		private System.DateTime _NgaySinhSV;
		
		private string _SdtSV;
		
		private string _MatKhauSV;
		
		public sp_TimKiemHoTenSVResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSV", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MaSV
		{
			get
			{
				return this._MaSV;
			}
			set
			{
				if ((this._MaSV != value))
				{
					this._MaSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTenSV", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string HoTenSV
		{
			get
			{
				return this._HoTenSV;
			}
			set
			{
				if ((this._HoTenSV != value))
				{
					this._HoTenSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lop", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Lop
		{
			get
			{
				return this._Lop;
			}
			set
			{
				if ((this._Lop != value))
				{
					this._Lop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinhSV", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string GioiTinhSV
		{
			get
			{
				return this._GioiTinhSV;
			}
			set
			{
				if ((this._GioiTinhSV != value))
				{
					this._GioiTinhSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinhSV", DbType="Date NOT NULL")]
		public System.DateTime NgaySinhSV
		{
			get
			{
				return this._NgaySinhSV;
			}
			set
			{
				if ((this._NgaySinhSV != value))
				{
					this._NgaySinhSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SdtSV", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string SdtSV
		{
			get
			{
				return this._SdtSV;
			}
			set
			{
				if ((this._SdtSV != value))
				{
					this._SdtSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhauSV", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MatKhauSV
		{
			get
			{
				return this._MatKhauSV;
			}
			set
			{
				if ((this._MatKhauSV != value))
				{
					this._MatKhauSV = value;
				}
			}
		}
	}
	
	public partial class sp_TimKiemMaSVResult
	{
		
		private string _MaSV;
		
		private string _HoTenSV;
		
		private string _Lop;
		
		private string _GioiTinhSV;
		
		private System.DateTime _NgaySinhSV;
		
		private string _SdtSV;
		
		private string _MatKhauSV;
		
		public sp_TimKiemMaSVResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSV", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MaSV
		{
			get
			{
				return this._MaSV;
			}
			set
			{
				if ((this._MaSV != value))
				{
					this._MaSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTenSV", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string HoTenSV
		{
			get
			{
				return this._HoTenSV;
			}
			set
			{
				if ((this._HoTenSV != value))
				{
					this._HoTenSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lop", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Lop
		{
			get
			{
				return this._Lop;
			}
			set
			{
				if ((this._Lop != value))
				{
					this._Lop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinhSV", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string GioiTinhSV
		{
			get
			{
				return this._GioiTinhSV;
			}
			set
			{
				if ((this._GioiTinhSV != value))
				{
					this._GioiTinhSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinhSV", DbType="Date NOT NULL")]
		public System.DateTime NgaySinhSV
		{
			get
			{
				return this._NgaySinhSV;
			}
			set
			{
				if ((this._NgaySinhSV != value))
				{
					this._NgaySinhSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SdtSV", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string SdtSV
		{
			get
			{
				return this._SdtSV;
			}
			set
			{
				if ((this._SdtSV != value))
				{
					this._SdtSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhauSV", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MatKhauSV
		{
			get
			{
				return this._MatKhauSV;
			}
			set
			{
				if ((this._MatKhauSV != value))
				{
					this._MatKhauSV = value;
				}
			}
		}
	}
	
	public partial class sp_TimKiemTacGiaResult
	{
		
		private string _MaSach;
		
		private string _TenSach;
		
		private string _ChuDe;
		
		private string _TacGia;
		
		private string _NhaXB;
		
		private string _NamXB;
		
		private string _SoLuong;
		
		private string _DonGia;
		
		private string _MaViTri;
		
		private string _MaSach1;
		
		private string _KhuVuc;
		
		private string _KeSach;
		
		private string _OSach;
		
		public sp_TimKiemTacGiaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSach", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MaSach
		{
			get
			{
				return this._MaSach;
			}
			set
			{
				if ((this._MaSach != value))
				{
					this._MaSach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSach", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenSach
		{
			get
			{
				return this._TenSach;
			}
			set
			{
				if ((this._TenSach != value))
				{
					this._TenSach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuDe", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ChuDe
		{
			get
			{
				return this._ChuDe;
			}
			set
			{
				if ((this._ChuDe != value))
				{
					this._ChuDe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TacGia", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TacGia
		{
			get
			{
				return this._TacGia;
			}
			set
			{
				if ((this._TacGia != value))
				{
					this._TacGia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhaXB", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NhaXB
		{
			get
			{
				return this._NhaXB;
			}
			set
			{
				if ((this._NhaXB != value))
				{
					this._NhaXB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamXB", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string NamXB
		{
			get
			{
				return this._NamXB;
			}
			set
			{
				if ((this._NamXB != value))
				{
					this._NamXB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this._SoLuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this._DonGia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaViTri", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MaViTri
		{
			get
			{
				return this._MaViTri;
			}
			set
			{
				if ((this._MaViTri != value))
				{
					this._MaViTri = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSach1", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MaSach1
		{
			get
			{
				return this._MaSach1;
			}
			set
			{
				if ((this._MaSach1 != value))
				{
					this._MaSach1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhuVuc", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string KhuVuc
		{
			get
			{
				return this._KhuVuc;
			}
			set
			{
				if ((this._KhuVuc != value))
				{
					this._KhuVuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeSach", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string KeSach
		{
			get
			{
				return this._KeSach;
			}
			set
			{
				if ((this._KeSach != value))
				{
					this._KeSach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OSach", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string OSach
		{
			get
			{
				return this._OSach;
			}
			set
			{
				if ((this._OSach != value))
				{
					this._OSach = value;
				}
			}
		}
	}
	
	public partial class sp_TimKiemTenSachResult
	{
		
		private string _MaSach;
		
		private string _TenSach;
		
		private string _ChuDe;
		
		private string _TacGia;
		
		private string _NhaXB;
		
		private string _NamXB;
		
		private string _SoLuong;
		
		private string _DonGia;
		
		private string _MaViTri;
		
		private string _MaSach1;
		
		private string _KhuVuc;
		
		private string _KeSach;
		
		private string _OSach;
		
		public sp_TimKiemTenSachResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSach", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MaSach
		{
			get
			{
				return this._MaSach;
			}
			set
			{
				if ((this._MaSach != value))
				{
					this._MaSach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSach", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenSach
		{
			get
			{
				return this._TenSach;
			}
			set
			{
				if ((this._TenSach != value))
				{
					this._TenSach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuDe", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ChuDe
		{
			get
			{
				return this._ChuDe;
			}
			set
			{
				if ((this._ChuDe != value))
				{
					this._ChuDe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TacGia", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TacGia
		{
			get
			{
				return this._TacGia;
			}
			set
			{
				if ((this._TacGia != value))
				{
					this._TacGia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhaXB", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NhaXB
		{
			get
			{
				return this._NhaXB;
			}
			set
			{
				if ((this._NhaXB != value))
				{
					this._NhaXB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamXB", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string NamXB
		{
			get
			{
				return this._NamXB;
			}
			set
			{
				if ((this._NamXB != value))
				{
					this._NamXB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this._SoLuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this._DonGia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaViTri", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MaViTri
		{
			get
			{
				return this._MaViTri;
			}
			set
			{
				if ((this._MaViTri != value))
				{
					this._MaViTri = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSach1", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MaSach1
		{
			get
			{
				return this._MaSach1;
			}
			set
			{
				if ((this._MaSach1 != value))
				{
					this._MaSach1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhuVuc", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string KhuVuc
		{
			get
			{
				return this._KhuVuc;
			}
			set
			{
				if ((this._KhuVuc != value))
				{
					this._KhuVuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeSach", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string KeSach
		{
			get
			{
				return this._KeSach;
			}
			set
			{
				if ((this._KeSach != value))
				{
					this._KeSach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OSach", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string OSach
		{
			get
			{
				return this._OSach;
			}
			set
			{
				if ((this._OSach != value))
				{
					this._OSach = value;
				}
			}
		}
	}
	
	public partial class sp_TongSoLuongSachResult
	{
		
		private System.Nullable<int> _SLSach;
		
		public sp_TongSoLuongSachResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLSach", DbType="Int")]
		public System.Nullable<int> SLSach
		{
			get
			{
				return this._SLSach;
			}
			set
			{
				if ((this._SLSach != value))
				{
					this._SLSach = value;
				}
			}
		}
	}
	
	public partial class sp_TongGiaTriSachResult
	{
		
		private System.Nullable<int> _GiaTri;
		
		public sp_TongGiaTriSachResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTri", DbType="Int")]
		public System.Nullable<int> GiaTri
		{
			get
			{
				return this._GiaTri;
			}
			set
			{
				if ((this._GiaTri != value))
				{
					this._GiaTri = value;
				}
			}
		}
	}
	
	public partial class sp_SoLuongSachDangMuonResult
	{
		
		private System.Nullable<int> _SLMuon;
		
		public sp_SoLuongSachDangMuonResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLMuon", DbType="Int")]
		public System.Nullable<int> SLMuon
		{
			get
			{
				return this._SLMuon;
			}
			set
			{
				if ((this._SLMuon != value))
				{
					this._SLMuon = value;
				}
			}
		}
	}
	
	public partial class sp_SoLuongSachDaMuonResult
	{
		
		private System.Nullable<int> _SLMuon;
		
		public sp_SoLuongSachDaMuonResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLMuon", DbType="Int")]
		public System.Nullable<int> SLMuon
		{
			get
			{
				return this._SLMuon;
			}
			set
			{
				if ((this._SLMuon != value))
				{
					this._SLMuon = value;
				}
			}
		}
	}
	
	public partial class sp_TimKiemTheoMaResult
	{
		
		private string _MaPhieuMuon;
		
		private string _MaSV;
		
		private string _MaSach;
		
		private string _NguoiLap;
		
		private string _SoLuong;
		
		private System.DateTime _NgayMuon;
		
		private System.DateTime _NgayTra;
		
		private string _GhiChu;
		
		public sp_TimKiemTheoMaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieuMuon", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MaPhieuMuon
		{
			get
			{
				return this._MaPhieuMuon;
			}
			set
			{
				if ((this._MaPhieuMuon != value))
				{
					this._MaPhieuMuon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSV", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MaSV
		{
			get
			{
				return this._MaSV;
			}
			set
			{
				if ((this._MaSV != value))
				{
					this._MaSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSach", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MaSach
		{
			get
			{
				return this._MaSach;
			}
			set
			{
				if ((this._MaSach != value))
				{
					this._MaSach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiLap", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string NguoiLap
		{
			get
			{
				return this._NguoiLap;
			}
			set
			{
				if ((this._NguoiLap != value))
				{
					this._NguoiLap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this._SoLuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayMuon", DbType="Date NOT NULL")]
		public System.DateTime NgayMuon
		{
			get
			{
				return this._NgayMuon;
			}
			set
			{
				if ((this._NgayMuon != value))
				{
					this._NgayMuon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTra", DbType="Date NOT NULL")]
		public System.DateTime NgayTra
		{
			get
			{
				return this._NgayTra;
			}
			set
			{
				if ((this._NgayTra != value))
				{
					this._NgayTra = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(200)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this._GhiChu = value;
				}
			}
		}
	}
	
	public partial class sp_SoLuongDGDangMuonResult
	{
		
		private System.Nullable<int> _Column1;
		
		public sp_SoLuongDGDangMuonResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int")]
		public System.Nullable<int> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class sp_SoLuongDGQuaHanResult
	{
		
		private System.Nullable<int> _SQLDGQuaHan;
		
		public sp_SoLuongDGQuaHanResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SQLDGQuaHan", DbType="Int")]
		public System.Nullable<int> SQLDGQuaHan
		{
			get
			{
				return this._SQLDGQuaHan;
			}
			set
			{
				if ((this._SQLDGQuaHan != value))
				{
					this._SQLDGQuaHan = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
